# Generated by Django 3.2 on 2023-04-14 12:00

from django.db import migrations, models

def create_initial_reactors(apps, schema_editor):
    Reactor = apps.get_model('reactors', 'Reactor')
    Reactor.objects.create(
        name='Continuous Stirred-Tank Reactor (CSTR)',
        description='A CSTR operates continuously, with reactants continuously added and products continuously removed. The contents are well-mixed, ensuring uniform composition throughout the reactor.',
        benefits='Simple design, easy operation, and good for liquid-phase reactions.',
        uses='Commonly used in chemical and pharmaceutical industries for reactions like polymerization, fermentation, and wastewater treatment.',
        reactor_type='CSTR'
    )
    Reactor.objects.create(
        name='Plug Flow Reactor (PFR)',
        description='In a PFR, reactants flow through a cylindrical pipe where the reaction occurs as the flow progresses. There is no back-mixing, and the composition varies along the length of the reactor.',
        benefits='High conversion per unit volume for first-order reactions, efficient for reactions with a single, irreversible reaction mechanism.',
        uses='Widely used in gas-phase and catalytic reactions, common in the production of chemicals like ammonia, sulfuric acid, and ethylene.',
        reactor_type='PFR'
    )
    Reactor.objects.create(
        name='Packed Bed Reactor (PBR)',
        description='A PBR consists of a bed of solid catalyst particles through which the reactants flow. The reaction occurs on the surface of the catalyst particles.',
        benefits='High surface area for reaction due to the packed bed of catalysts, suitable for exothermic reactions as the heat can be removed effectively.',
        uses='Commonly used in industrial catalytic processes like hydrogenation, oxidation, and methanation.',
        reactor_type='PBR'
    )
    Reactor.objects.create(
        name='Batch Reactor',
        description='A Batch Reactor is a closed system where all reactants are loaded, and the reaction is allowed to proceed with no inflow or outflow until the reaction is complete.',
        benefits='Flexibility in operation, ideal for small-scale production and testing.',
        uses='Frequently used in pharmaceutical and specialty chemical production, suitable for producing small volumes of high-value products.',
        reactor_type='BATCH'
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('uses', models.TextField()),
                ('reactor_type', models.CharField(choices=[('CSTR', 'Continuous Stirred-Tank Reactor'), ('PFR', 'Plug Flow Reactor'), ('PBR', 'Packed Bed Reactor'), ('BATCH', 'Batch Reactor')], max_length=5)),
            ],
        ),
        migrations.RunPython(create_initial_reactors),
    ]